config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root 'static_pages#home'

  resources :users, only: [:show]
  resources :rooms
 
  resources :rooms do
    resources :images, only: [:create, :destroy]
    resources :bookings
    member do
      get :listing
      get :price
      get :description
      get :photo
      get :amenities
      get :location
      get :check_current_bookings
      get :review_booking
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  validates :home_type, presence: true
  validates :room_type, presence: true
  validates :accomodate, presence: true
  validates :bedroom, presence: true
  validates :bathroom, presence: true

  has_many :images
  has_many :user
  has_many :bookings

  geocoded_by :location
  after_validation :geocode
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :fetch_room, except: [:new, :create, :index]
  include RoomsHelper
  def new
    @room = Room.new
  end

  def listing
  end
  def amenities
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      flash[:success] = "Saved succesfully"
      redirect_to listing_room_path(@room)
    else
      flash[:danger] = "Invalid content.Try again "
      redirect_back(fallback_location: root_path)
    end
  end

   def update
    @final_data = is_ready_to_publish(@room) ? room_params.merge(is_active: true) : room_params.merge(is_active: false)
    if @room.update_attributes(@final_data)
      flash[:notice] = 'Updated Listing Details!'
    else
      flash[:alert] = 'Update Failed!'
    end
    redirect_back(fallback_location: root_path)
  end

  def photo
    @images = @room.images
  end

  def show
    @user = User.find(@room.user_id)
    @carousel = @room.images
  end

  
   
  def check_current_bookings
    today = Date.today
    booking = @room.bookings.where("check_in_date >= ? OR check_out_date >= ?", today, today)

    render json: booking
  end

 def review_booking
    check_in_date = Date.parse(params[:check_in_date])
    check_out_date = Date.parse(params[:check_out_date])

    result = { conflict: check_conflicts(check_in_date, check_out_date, @room) }

    render json: result
  end

    private
    def room_params
      params.require(:room).permit(:home_type, :room_type, :accomodate, :bedroom, :bathroom,:price,:description,:photo,:kitchen,:tv,:internet,:air_conditioner,:heating,:location,:room_name,:user_id,:is_active) 
    end

    def fetch_room
      if params[:room_id].present?
        @room = Room.find(params[:room_id])
      else
        @room = Room.find(params[:id])
      end
    end

    def check_conflicts(check_in_date, check_out_date, room)
      check = @room.bookings.where('? < check_in_date AND check_out_date < ?', check_in_date, check_out_date)
      check.size > 0 ? true : false
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  
  def is_ready_to_publish(room)
    room.location.present? && room.description.present? && room.room_name.present? && room.price.present? && room.images.present?
  end

end

app/views/rooms/_listing.side.html.erb
<br><br>
<div class="container mt-3">
    <div class="row">
        <div class="col-3">
            <div class="card">
                <div class="card-body">
                    <h4>
                        <div>
                            <%= link_to "Listing", room_images_path(@room),class:"text-info"%>
                            <span class="float-right">
                            <%if @room.home_type.present? %><i class="fa fa-check"></i><% else %>
                            <%if @room.room_type.present? %><i class="fa fa-check"></i><% else %>
                            <%if @room.accomodate.present? %><i class="fa fa-check"></i><% else %>
                            <%if @room.bedroom.present? %><i class="fa fa-check"></i><% else %>
                            <%if @room.bathroom.present? %><i class="fa fa-check"></i><% else %>
                            <% end %><% end %><% end %><% end %><% end %>
                        </div>
                    </h4>
                    <h4>
                        <div>
                            <%= link_to "Price", price_room_path(@room),class:"text-info"%>
                            <span class="float-right">
                            <% if @room.price.present? %><i class="fa fa-check"></i><% else %><% end %>
                        </div>
                    </h4>
                    <h4>
                        <div>
                            <%= link_to "Description", description_room_path(@room),class:"text-info"%>
                            <span class="float-right">
                            <% if @room.description.present? %><i class="fa fa-check"></i><% else %><% end %>
                        </div>
                    </h4>        
                    <h4>
                        <div>
                            <%= link_to "Photos", photo_room_path(@room),class:"text-info"%>
                            <span class="float-right">
                            <% if @room.images.first.present? %><i class="fa fa-check"></i><% else %><% end %>
                        </div>
                    </h4>
                    <h4>
                        <div>
                            <%= link_to "Amenities", amenities_room_path(@room),class:"text-info"%>
                            <span class="float-right">
                            <%if @room.tv.present? %><i class="fa fa-check"></i><% else %>
                            <%if @room.kitchen.present? %><i class="fa fa-check"></i><% else %>
                            <%if @room.internet.present? %><i class="fa fa-check"></i><% else %>
                            <%if @room.heating.present? %><i class="fa fa-check"></i><% else %>
                            <%if @room.air_conditioner.present? %><i class="fa fa-check"></i><% else %>
                            <% end %><% end %><% end %><% end %><% end %>
                        </div>
                    </h4>
                    <h4>
                        <div>
                        <%= link_to "Location", location_room_path(@room),class:"text-info"%>  
                         <span class="float-right">
                         <% if @room.location.present? %><i class="fa fa-check"></i><% else %><% end %>
                        </div>
                    </h4>
                    <hr>
                    <div class="actions text-center">
                    <%= form_for(@room) do |f| %>
                        <%= f.hidden_field :is_active, value:true %>
                        <%= f.submit "Publish", disabled: !is_ready_to_publish(@room), class: "btn btn-primary" %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>

app/views/rooms/amenities.html.erb
<%= render 'rooms/listing.side' %>
    <div class="col-9">
        <div class="card">
            <div class="card-header">Amenities</div>
                <div class="card-body">
                    <div class="row">
                        <%= form_for(@room) do |f| %>
                            <div class="col">
                                <div class="form-group">
                                    <%= f.check_box :tv%>TV
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group">
                                    <%= f.check_box :kitchen %>kitchen
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group">
                                    <%= f.check_box :internet %>internet
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group">
                                    <%= f.check_box :heating %>Heating
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group">
                                <%= f.check_box :air_conditioner %>Air conditioner
                                </div>
                            </div>  
                            <div>
                                <%= f.submit "Save", class:"btn btn-dark" %>
                            </div>      
                        <% end %>  
                    </div>
                </div>
            </div>                            
        </div>
    </div>

app/views/rooms/description.html.erb
<%= render 'rooms/listing.side' %>
    <div class="col-9">
        <div class="card">
            <div class="card-header theme-color">Description</div>
                <div class="card-body">
                <%= form_for(@room) do |f| %>
                    <div class="form-group">
                        <label>Listing name</label>
                        <%= f.text_field :room_name , autofocus: true, autocomplete: "listing_name",:placeholder =>"What is your listing name?" ,class:"form-control",required: true%>
                    </div>
                    <div class="form-group">
                        <label>Summary</label>
                            <%= f.text_field :description , autofocus: true, autocomplete: "summary",:placeholder =>"Summary of your house" ,class:"form-control",required: true %>
                        </div>   
                        <div class="form-group mt-2">
                            <%= f.submit "Save", class:"btn btn-dark" %>
                        </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/rooms/listing.html.erb
 
<%= render 'rooms/listing.side' %>
        <div class="col-9">
            <div class="card">
                <div class="card-header">
                    <h5>Listing</h5>
                </div>
                <div class="card-body">
                    <%= form_for(@room) do |f| %>
                        <div class="row">
                            <div class="col-4 select">
                                <div class="form-group">
                                    <label for="home_type">Home type</label>
                                 <%= f.select :home_type, options_for_select([
                                        ["Select..."],
                                        ["Apartment"],
                                        ["Resort"],
                                        ["House"],
                                        ["Bread & Breakfast"]
                                    ], selected: f.object.home_type), {}, class: "form-control"%>
                                </div>
                            </div>

                            <div class="col-4 select">
                                <div class="form-group">
                                    <label for="room_type">Room type</label>
                                    <%= f.select :room_type, options_for_select([
                                        ["Select..."],
                                        ["Entire"],
                                        ["Private"],
                                        ["Shared"],
                                    ], selected: f.object.room_type), {}, class: "form-control"%>
                                </div>
                            </div>

                            <div class="col-4 select">
                                <div class="form-group">
                                    <label for="accomodate">Accomodate</label>
                                    <%= f.select :accomodate, options_for_select([
                                        ["Select..."],
                                        ["1"],
                                        ["2"],
                                        ["3"],
                                        ["4"]
                                    ], selected: f.object.accomodate), {}, class:"form-control"%>
                                </div>
                            </div>
                            <div class="col-4 select">
                                <div class="form-group">
                                    <label for="bedroom">Bedroom</label>
                                    <%= f.select :bedroom, options_for_select([
                                        ["Select..."],
                                        ["1"],
                                        ["2"],
                                        ["3"],
                                        ["4"]
                                    ], selected: f.object.bedroom), {}, class: "form-control"%>
                                </div>
                            </div>

                            <div class="col-4 select">
                                <div class="form-group">
                                    <label for="bathroom">Bathroom</label>
                                     <%= f.select :bathroom, options_for_select([
                                        ["Select..."],
                                        ["1"],
                                        ["2"],
                                        ["3"],
                                        ["4"]
                                    ], selected: f.object.bathroom), {}, class: "form-control"%>
                                </div>
                            </div>        
                        </div>
                        
                        <div class="form-group mt-2">
                            <%= f.submit "Save", class:"btn btn-dark" %>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
                   

app/views/rooms/location.html.erb
<%= render 'rooms/listing.side' %>
<div class="col-9">
    <div class="card">
        <div class="card-header">
            <h5>Location</h5>
        </div>
        <div class="card-body">
            <%= form_for(@room) do |f| %>
                <div class="form-group">
                    <label for="room_address">Address</label>
                    <div class="form-group">
                        <%= f.text_field :location , autofocus: true, autocomplete: "location",:placeholder =>"Where is your address?" ,class:"form-control",required: true %>
                    </div>
                </div>
                <div class="form-group mt-2">
                    <%= f.submit "Save", class:"btn btn-dark" %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/rooms/new.html.erb
<br>
<div class="container mt-3">
    <div class="card">
        <div class="card-header theme-color">Create your beautiful place</div>
            <div class="card-body">
                <%= form_for(@room) do |f| %>
                    <%= f.hidden_field :is_active, value: false %>
                    <%= f.hidden_field :user_id, value: user_signed_in? ? current_user.id : nil %>
                    <div class="row">
                        <div class="col-4 select">
                            <div class="form-group">
                                <label for="home_type">Home type</label>
                                <%= f.select :home_type, options_for_select([
                                ["Select .."],
                                ["Apartment"],
                                ["House"],
                                ["Bed&Breakfast"]]),{}, class: "form-control" %>
                            </div>
                        </div>

                        <div class="col-4 select">
                            <div class="form-group">
                                <label for="room_type">Room type</label>
                                <%= f.select :room_type, options_for_select([
                                ["Select .."],
                                ["Entire"],
                                ["Private"],
                                ["Shared"]]), {}, class: "form-control" %>
                            </div>
                        </div>

                        <div class="col-4 select">
                            <div class="form-group">
                                <label for="accomodate">Accomodate</label>
                                <%= f.select :accomodate, options_for_select([
                                ["Select .."],
                                ["1"],
                                ["2"],
                                ["3"],
                                ["4"]]), {}, class: "form-control" %>
                                
                            </div>
                        </div>
                        <div class="col-4 select">
                            <div class="form-group">
                                <label for="bedroom">Bedroom</label>
                                 <%= f.select :bedroom, options_for_select([
                                ["Select .."],
                                ["1"],
                                ["2"],
                                ["3"],
                                ["4"]]), {}, class: "form-control" %>
                            </div>
                        </div>

                        <div class="col-4 select">
                            <div class="form-group">
                                <label for="bathroom">Bathroom</label>
                                 <%= f.select :bathroom, options_for_select([
                                ["Select .."],
                                ["1"],
                                ["2"],
                                ["3"],
                                ["4"]]), {}, class: "form-control" %>
                            </div>
                        </div>        
                    </div>
                    <div class="form-group mt-2">
                        <%= f.submit "Create my room", class:"btn btn-dark" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/rooms/photo.html.erb
<%= render 'rooms/listing.side' %>
<div class="col-9">
    <div class="card">
        <div class="card-header">Photo Upload</div>
            <div class="card-body text-center">
                <div class="row">
                    <%= form_for @room, url: room_images_url(@room), method: "post", html: { :multipart => true }, enctype: 'multipart/form-data' do |f| %>
                            <%= file_field_tag "images[]", type: :file, multiple: true, required: true, accept: "image/jpeg,image/gif,image/png" %>
                        <div class="row">
                        <% @images.each do |image| %>
                            <div class="col col-lg-4 py-2">
                                <div class="card mt-4">
                                    <div class="card-img-top-preview"> 
                                        <%= image_tag image.image, class: "img mw-100" %>
                                    </div>
                                    <div class="card-text">
                                        <%= link_to raw("<i class=' fa fa-trash text-danger'></i>&nbsp;Delete image"), room_image_path(@room, image), method: :delete, class: "ext-danger" %>
                                    </div>
                                </div>                            
                            </div>
                        <% end %>
                        </div>
                        <div class="form-group mt-2">
                            <%= f.submit "Add Photos", class:"btn btn-dark" %>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/rooms/price.html.erb
<%= render 'rooms/listing.side' %>
    <div class="col-9">
        <div class="card">                
            <div class="card-header">
                <h5>Price</h5>
            </div>
            <div class="card-body">
                <%= form_for(@room) do |f| %>
                <div class="form-group">
                    <label for="room_price">Price</label>
                        <div class="form-group">
                                <%= f.number_field :price , autofocus: true, autocomplete: "price",:placeholder =>"Price" ,class:"form-control",required: true %>
                        </div>
                </div>
                <div class="form-group mt-2">
                    <%= f.submit "Save", class:"btn btn-dark" %>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</div>