config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root 'static_pages#home'

  resources :users, only: [:show]
  resources :rooms
 
  resources :rooms do
    resources :images, only: [:create, :destroy]
    resources :bookings
    member do
      get :listing
      get :price
      get :description
      get :photo
      get :amenities
      get :location
      get :check_current_bookings
      get :review_booking
    end
  end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md fixed-top bg-light">
    <div class="body">
        <strong><%= link_to "y-airbnb",root_path,class:"nav-link text-dark" %></strong>
    </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <input class="form-control mr-sm-2" type="search" placeholder="Where are you going?" aria-label="Search">
            </li>
            <li class="nav-item">
                <a class="btn btn-outline-success" href="/rooms/new">Become a host</a>
            </li>
            <% if user_signed_in? %>
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle text-muted" data-toggle="dropdown">
                        <%= current_user.name %><b class="caret"></b>
                    </a>
                        <li class="nav-item ">
                            <%= link_to "Manage Listring","",class:"nav-link text-muted" %>
                        </li>
                        <li class="nav-item ">
                            <%= link_to "List Your Space",new_room_path,class:"nav-link text-muted" %>
                        </li>
                        <li class="nav-item ">
                            <%= link_to "Your Reservations","",class:"nav-link text-muted" %>
                        </li>
                        <br>
                        <li class="nav-item ">
                            <%= link_to "Edit Profile",edit_user_registration_path,class:"nav-link text-muted" %>
                        </li>
                        <br>
                        <li class="nav-item ">
                            <%= link_to "Profile",user_path(current_user.id),class:"nav-link text-muted" %>
                        </li>
                        <li class="nav-item ">
                            <%= link_to "Log Out",destroy_user_session_path,method: :delete,class:"nav-link text-muted" %>
                        </li>
                </li>
            <% else %>
                    <li class="nav-item ">
                        <%= link_to "Login",new_user_session_path ,class:"nav-link text-muted" %>
                    </li>
                    <li class="nav-item ">
                        <%= link_to "Sign up",new_user_registration_path,class:"nav-link text-muted"%>
                    </li>
            <% end %>
        </ul>
        </div>
    </div>
</nav>
           

app/views/layouts/application.html.erb
<!DOCTYPE html>
    <html>
        <head>
            <title><%= yield(:title) %>| Airbnb-Clone</title>
            <title>AirbnbClone</title>
            <div class="mt-5">
            <%= csrf_meta_tags %>
           <%= csp_meta_tag %>
           
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
            <%= stylesheet_link_tag 'application', media: 'all','data-turbolinks-track': 'reload' %>
            <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        </head>
        <body>
            <div class="container">
                    <%= render 'layouts/header' %>
                    <%= custom_bootstrap_flash %>
                   
                    </div>
                <%= yield %>
            </div>
        </body>
    </html>